export const SKILL_LIST = ['Next.js', 'React', 'Angular', 'JavaScript', 'TypeScript']

export const TECH_ICONS = [
	{ path: '/assets/icons/tech/CSS3.svg', alt: 'CSS3', title: 'CSS3' },
	{ path: '/assets/icons/tech/Cypress.svg', alt: 'Cypress', title: 'Cypress' },
	{ path: '/assets/icons/tech/Gatsby.svg', alt: 'Gatsby', title: 'Gatsby' },
	{ path: '/assets/icons/tech/Git.svg', alt: 'Git', title: 'Git' },
	{
		path: '/assets/icons/tech/GitHub.svg',
		alt: 'GitHub',
		title: 'GitHub',
	},
	{
		path: '/assets/icons/tech/GitHub_Actions.svg',
		alt: 'GitHub Actions',
		title: 'GitHub Actions',
	},
	{ path: '/assets/icons/tech/HTML5.svg', alt: 'HTML5', title: 'HTML5' },
	{ path: '/assets/icons/tech/JavaScript.svg', alt: 'JavaScript', title: 'JavaScript' },
	{ path: '/assets/icons/tech/Jira.svg', alt: 'Jira', title: 'Jira' },
	{ path: '/assets/icons/tech/Less.js.svg', alt: 'Less.js', title: 'Less.js' },
	{
		path: '/assets/icons/tech/Next.js.svg',
		alt: 'Next.js',
		title: 'Next.js',
	},
	{ path: '/assets/icons/tech/Node.js.svg', alt: 'Node.js', title: 'Node.js' },
	{ path: '/assets/icons/tech/React.svg', alt: 'React', title: 'React' },
	{ path: '/assets/icons/tech/Redux.svg', alt: 'Redux', title: 'Redux' },
	{ path: '/assets/icons/tech/Sass.svg', alt: 'Sass', title: 'Sass' },
	{ path: '/assets/icons/tech/Tailwind_CSS.svg', alt: 'Tailwind CSS', title: 'Tailwind CSS' },
	{ path: '/assets/icons/tech/TypeScript.svg', alt: 'TypeScript', title: 'TypeScript' },
	{
		path: '/assets/icons/tech/Vercel.svg',
		alt: 'Vercel',
		title: 'Vercel',
	},
	{ path: '/assets/icons/tech/Vite.js.svg', alt: 'Vite.js', title: 'Vite.js' },
	{ path: '/assets/icons/tech/Webpack.svg', alt: 'Webpack', title: 'Webpack' },
	{ path: '/assets/icons/tech/Yarn.svg', alt: 'Yarn', title: 'Yarn' },
	{ path: '/assets/icons/tech/NPM.svg', alt: 'NPM', title: 'NPM' },
	{ path: '/assets/icons/tech/Karma.svg', alt: 'Karma', title: 'Karma' },
	{ path: '/assets/icons/tech/JSON.svg', alt: 'JSON', title: 'JSON' },
	{ path: '/assets/icons/tech/Jest.svg', alt: 'Jest', title: 'Jest' },
	{ path: '/assets/icons/tech/Jamstack.svg', alt: 'Jamstack', title: 'Jamstack' },
	{ path: '/assets/icons/tech/GraphQL.svg', alt: 'GraphQL', title: 'GraphQL' },
	{ path: '/assets/icons/tech/GitLab.svg', alt: 'GitLab', title: 'GitLab' },
	{ path: '/assets/icons/tech/Figma.svg', alt: 'Figma', title: 'Figma' },
	{ path: '/assets/icons/tech/ESLint.svg', alt: 'ESLint', title: 'ESLint' },
	{ path: '/assets/icons/tech/Docker.svg', alt: 'Docker', title: 'Docker' },
]
