export const SKILL_LIST = ['Next.js', 'React', 'Angular', 'JavaScript', 'TypeScript']

export const TECH_ICONS = [
	{ path: '/assets/icons/tech/CSS3.svg', alt: 'CSS3' },
	{ path: '/assets/icons/tech/Cypress.svg', alt: 'Cypress' },
	{ path: '/assets/icons/tech/Gatsby.svg', alt: 'Gatsby' },
	{ path: '/assets/icons/tech/Git.svg', alt: 'Git' },
	{ path: '/assets/icons/tech/GitHub.svg', alt: 'GitHub', className: 'dark:bg-white' },
	{ path: '/assets/icons/tech/GitHub_Actions.svg', alt: 'GitHub Actions' },
	{ path: '/assets/icons/tech/HTML5.svg', alt: 'HTML5' },
	{ path: '/assets/icons/tech/JavaScript.svg', alt: 'JavaScript' },
	{ path: '/assets/icons/tech/Jira.svg', alt: 'Jira' },
	{ path: '/assets/icons/tech/Less.js.svg', alt: 'Less.js' },
	{ path: '/assets/icons/tech/Next.js.svg', alt: 'Next.js', className: 'dark:bg-white' },
	{ path: '/assets/icons/tech/Node.js.svg', alt: 'Node.js' },
	{ path: '/assets/icons/tech/React.svg', alt: 'React' },
	{ path: '/assets/icons/tech/Redux.svg', alt: 'Redux' },
	{ path: '/assets/icons/tech/Sass.svg', alt: 'Sass' },
	{ path: '/assets/icons/tech/Tailwind_CSS.svg', alt: 'Tailwind CSS' },
	{ path: '/assets/icons/tech/TypeScript.svg', alt: 'TypeScript' },
	{ path: '/assets/icons/tech/Vercel.svg', alt: 'Vercel', className: 'dark:bg-white' },
	{ path: '/assets/icons/tech/Vite.js.svg', alt: 'Vite.js' },
	{ path: '/assets/icons/tech/Webpack.svg', alt: 'Webpack' },
	{ path: '/assets/icons/tech/Yarn.svg', alt: 'Yarn' },
	{ path: '/assets/icons/tech/NPM.svg', alt: 'NPM' },
	{ path: '/assets/icons/tech/Karma.svg', alt: 'Karma' },
	{ path: '/assets/icons/tech/JSON.svg', alt: 'JSON' },
	{ path: '/assets/icons/tech/Jest.svg', alt: 'Jest' },
	{ path: '/assets/icons/tech/Jamstack.svg', alt: 'Jamstack' },
	{ path: '/assets/icons/tech/GraphQL.svg', alt: 'GraphQL' },
	{ path: '/assets/icons/tech/GitLab.svg', alt: 'GitLab' },
	{ path: '/assets/icons/tech/Figma.svg', alt: 'Figma' },
	{ path: '/assets/icons/tech/ESLint.svg', alt: 'ESLint' },
	{ path: '/assets/icons/tech/Docker.svg', alt: 'Docker' },
]
