export const ITEMS = [
	{
		title: 'Soft Skills',
		subtitle: 'Interpersonal and communication skills essential for collaboration and growth:',
		skills: [
			{ name: 'Communication' },
			{ name: 'Teamwork' },
			{ name: 'Problem-Solving' },
			{ name: 'Time Management' },
			{ name: 'Adaptability' },
			{ name: 'Critical Thinking' },
			{ name: 'Emotional Intelligence' },
			{ name: 'Leadership' },
		],
	},
	{
		title: 'Hard Skills',
		subtitle: 'Technical expertise and tools mastered:',
		skills: [
			{ name: 'CSS3' },
			{ name: 'Cypress' },
			{ name: 'Gatsby' },
			{ name: 'Git' },
			{ name: 'GitHub' },
			{ name: 'GitHub Actions' },
			{ name: 'HTML5' },
			{ name: 'JavaScript' },
			{ name: 'Jira' },
			{ name: 'Less.js' },
			{ name: 'Next.js' },
			{ name: 'Node.js' },
			{ name: 'React' },
			{ name: 'Angular' },
			{ name: 'RxJS' },
			{ name: 'NgRx' },
			{ name: 'Redux' },
			{ name: 'Sass' },
			{ name: 'Tailwind CSS' },
			{ name: 'TypeScript' },
			{ name: 'Vercel' },
			{ name: 'Vite.js' },
			{ name: 'Webpack' },
			{ name: 'Yarn' },
			{ name: 'NPM' },
			{ name: 'Karma' },
			{ name: 'JSON' },
			{ name: 'Jest' },
			{ name: 'Jamstack' },
			{ name: 'GraphQL' },
			{ name: 'GitLab' },
			{ name: 'Figma' },
			{ name: 'ESLint' },
			{ name: 'Docker' },
		],
	},
]
