export const EXPERIENCE_LIST = [
  {
    id: 1,
    logo: "https://assets.maccarianagency.com/svg/logos/slack.svg",
    company: "Kapsys Pages",
    role: "Middle+ Front-End Developer",
    duration: "2023 - Present",
    responsibilities: [
      "👥 Worked in 3 teams and contributed to 10+ projects.",
      "⚡ Developed highly SEO-optimized, high-performance applications using SSG (Static Site Generation) with Next.js.",
      "🛠️ Built and maintained component libraries with shadcn across multiple projects, improving development efficiency and UI consistency.",
      "🚀 Migrated 2+ large-scale applications to Next.js, improving SEO, performance, and maintainability.",
      "⚡ Optimized data fetching and state management in 3+ applications using React Query, improving performance and reducing unnecessary re-renders.",
      "🎨 Developed 5+ projects using Tailwind CSS, ensuring consistent and scalable UI components.",
    ],
  },
  {
    id: 2,
    logo: "https://assets.maccarianagency.com/svg/logos/slack.svg",
    company: "Interwetten",
    role: "Front-End Developer",
    duration: "2024",
    responsibilities: [
      "⚽ Built a microfrontend SSR Next.js sports blog, displaying real-time sports content on page load with latency under 500ms.",
      "🎰 Developed a custom Kontent AI component to manage and display live bets on the website, improving content editor efficiency by 40% and enhancing user engagement by 30%.",
      "⚡ Reduced page load times by 40% by implementing advanced code-splitting techniques with Next.js.",
      "🎯 Achieved a 25% boost in application performance by optimizing critical path CSS and implementing lazy loading.",
    ],
  },
  {
    id: 3,
    logo: "https://assets.maccarianagency.com/svg/logos/slack.svg",
    company: "Seobase",
    role: "Middle+ Front-End Developer",
    duration: "2022 - 2024",
    responsibilities: [
      "📈 Implemented five product features helping users boost rankings by 20-40%.",
      "🛠️ Built a scalable platform using Angular, supporting 100,000+ users and providing SEO tools for rank tracking.",
      "🚀 Increased page speed by 30% by converting project from Angular to SSR Next.js.",
      "📊 Integrated Chart.js and PrimeReact, providing interactive data visualization for business insights.",
    ],
  },
  {
    id: 4,
    logo: "https://assets.maccarianagency.com/svg/logos/slack.svg",
    company: "All American Home Care LLC",
    role: "Junior Angular Developer",
    duration: "2021 - 2022",
    responsibilities: [
      "🛠️ Developed a custom CRM system using Angular, streamlining caregiver management, patient records, and scheduling, handling 10,000+ records seamlessly.",
      "⏳ Integrated real-time caregiver assignment, compliance tracking, and automated scheduling, improving task allocation accuracy by 95%.",
      "🤖 Automated workflows, reducing manual administrative tasks by 40% and cutting scheduling time from 20 minutes to 5 minutes per request.",
      "📈 Increased team productivity by enabling the handling of 20% more cases per week without additional staff, significantly boosting operational capacity.",
      "✅ Enhanced data accuracy by improving record-keeping precision by 98%, minimizing errors in patient records and caregiver assignments.",
    ],
  },
]
